[package]
name = "sqrt2"
version = "0.1.0"
authors = ["sam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.6.0"
bigdecimal = "0.1.2"


